apiVersion: v1
kind: Pod
metadata:
  name: greetings
  labels:
    name: greetings
spec:
  containers:
    - image: us.gcr.io/cloudark-test-gke/greetpod:1512924392448
      name: greetpod
      ports:
      - containerPort: 5000
      env:
        - name: "PASSWORD"
          value: testpass123!@#
        - name: "DB"
          value: testdb
        - name: "HOST"
          value: 35.225.61.225
        - name: "USER"
          value: root
